update build config (nix+cabal or stack+cabal)
guibou/TapTempo pull request #1
Opened 2018-03-18 20:32 UTC by nokomprendo

Hi Guillaume,
here is a new config for building TapTempo. 
It works on nixos 17.09 and may also work using stack.
See the end of the `README.md` file for some minor problems.

2018-03-18 23:04 UTC, guibou commented on default.nix
> +with import <unstable> {};
Why `<unstable>` ?

2018-03-18 23:04 UTC, guibou commented on src/Main.hs
> +  "Tap Tempo " -- TODO ++ $(versionString)
This PR breaks one of the core feature of this version of TapTempo, why?

2018-03-18 23:04 UTC, guibou commented on default.nix
> +if lib.inNixShell then drv.env else drv
Why this case on `inNixShell`?

2018-03-18 23:04 UTC, guibou commented on default.nix
> +with import <unstable> {};
We may replace it by a pinned channel (or a pinned `nixpkgs` commit), such as:

```nix
with import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/13e74a838db27825c88be99b1a21fbee33aa6803.tar.gz") {};
```

2018-03-18 23:19 UTC, guibou requested changes
Restore the git behavior as suggested and fix the default.nix and I'll merge ;)

2018-03-18 23:19 UTC, guibou commented on default.nix
> +  drv = haskellPackages.callCabal2nix "TapTempo" ./. {};
Where is `git` dependency? This should do it:

```nix
drv = (haskellPackages.callCabal2nix "TapTempo" ./. {}).overrideAttrs(oldAttrs :
{
   buildInputs = oldAttrs.buildInputs ++ [git];
});
```

2018-03-19 10:10 UTC, nokomprendo commented on default.nix
> +with import <unstable> {};
ok, fixed

2018-03-19 10:10 UTC, nokomprendo commented on default.nix
> +  drv = haskellPackages.callCabal2nix "TapTempo" ./. {};
fixed

2018-03-19 10:12 UTC, nokomprendo commented on src/Main.hs
> +  "Tap Tempo " -- TODO ++ $(versionString)
There was a problem in the readProcess command. Now it works using `git describe --long --all`.

2018-03-19 10:15 UTC, nokomprendo commented on default.nix
> +if lib.inNixShell then drv.env else drv
This makes it possible to use `nix-build` and `nix-shell` with a single `default.nix` file. Otherwise, we have to write a `shell.nix` file or use `nix-shell -A env`.

2018-03-19 10:16 UTC, merged

2018-03-19 10:22 UTC, guibou commented on default.nix
> +if lib.inNixShell then drv.env else drv
Ok. I did not have that problem before, but it may be an issue with `callCabal2nix`.

2018-03-19 10:24 UTC, guibou commented on src/Main.hs
> +  "Tap Tempo " -- TODO ++ $(versionString)
I removed `--long --all`, it does not provide the output I want: `tags/0.1.2-0-ga09725c` versus `0.1.2`.

2018-03-19 10:25 UTC, guibou commented
Thank you.